MyCard.Web/Models/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCard.Web.Models
{
    public class ChangePasswordViewModel
    {
        //[Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "OldPasswordRequired")]
        [Display(Name = "OldPassword", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        [DataType(DataType.Password)]
        public string OldPassword { get; set; }
       // [Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "PasswordRequired")]
        [Display(Name = "Password", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        //[StringLength(255, ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "PasswordLengthErrorMessage", MinimumLength = 8)]
        [DataType(DataType.Password)]
        //[RegularExpression("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$", ErrorMessageResourceType = typeof(Resources.ErrorMessages), ErrorMessageResourceName = "InvalidPassword")]
        public string Password { get; set; }
        //[Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "ConfirmPasswordRequired")]
        [Display(Name = "ConfirmPassword", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "ComparePasswordErrorMessage")]
        public string ConfirmPassword { get; set; }
    }
}

MyCard.Web/Models/CompanyDashboardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyCard.Web.Models
{
    public class CompanyDashboardViewModel
    {

        public string EmailID { get; set; }
        public string Name { get; set; }
        public string BusinessTitle { get; set; }
        public string CustomerName { get; set; }
        public string DomainName { get; set; }
        public int TotalPurchase { get; set; }
        public string LastPurchaseDate { get; set; }
        public string MemberSince { get; set; }
        public int TotalCompaniesCreated { get; set; }
        public int TotalCardsShared { get; set; }

    }
}

MyCard.Web/Models/CreatePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCard.Web.Models
{
    public class CreatePasswordViewModel
    {
        //[Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "PasswordRequired")]
        [Display(Name = "Password", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        //[StringLength(255, ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "PasswordLengthErrorMessage", MinimumLength = 8)]
        [DataType(DataType.Password)]
        //[RegularExpression("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$", ErrorMessageResourceType = typeof(Resources.ErrorMessages), ErrorMessageResourceName = "InvalidPassword")]
        public string Password { get; set; }
        //[Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "ConfirmPasswordRequired")]
        [Display(Name = "ConfirmPassword", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "ComparePasswordErrorMessage")]
        public string ConfirmPassword { get; set; }
    }
}

MyCard.Web/Models/EmployeeListingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCard.Web.Models
{
    public class EmployeeListingViewModel
    {
        public IList<EmployeeListViewModel> EmployeesList { get; set; }
        public int CurrentPageIndex { get; set; }
        public int PageSize { get; set; }
        public int PageCount { get; set; }
        public string SearchString { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public int CompanyID { get; set; }
    }
}

MyCard.Web/Models/ForgotPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCard.Web.Models
{
    public class ForgotPasswordViewModel
    {
        [Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "EmailRequired")]
        [EmailAddress(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "EmailValid")]
        [Display(Name = "EmailID", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        public string Email { get; set; }
    }
}

MyCard.Web/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCard.Web.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "UserNameRequired")]
        [Display(Name = "UserName", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        public string UserName { get; set; }
        [Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "PasswordRequired")]
        [Display(Name = "Password", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Display(Name = "RememberMe", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        public bool RememberMe { get; set; }
    }
}

MyCard.Web/Models/ResendLinkViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyCard.Web.Models
{
    public class ResendLinkViewModel
    {
        [Required(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "EmailRequired")]
        [EmailAddress(ErrorMessageResourceType = (typeof(MyCard.Web.Resources.ErrorMessages)), ErrorMessageResourceName = "EmailValid")]
        [Display(Name = "EmailID", ResourceType = typeof(MyCard.Web.Resources.CaptionsAll))]
        public string Email { get; set; }
    }
}

MyCard.Web/Controllers/CompanyDashboardController.cs
using MyCard.Web.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using MyCard.Domain;
using MyCard.Web.Models;
using MyCard.BoundedContext;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Threading;
using System.Web.Hosting;
using MyCard.Helper;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using System.Web.UI;
using System.Text;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.OpenIdConnect;
using MyCard.Web.Security;
using System.Security.Claims;
using MyCard.Web.TokenStorage;
using Microsoft.Owin.Security.Cookies;
using System.Net.Http;
using System.Security.Cryptography;
using CaptchaMvc.HtmlHelpers;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using MySql.Data.MySqlClient;

namespace MyCard.Web.Controllers
{
    [ErrorHandlerAttribute]
    [Authorize(Roles = "company_owner")]
    public class CompanyDashboardController : Controller
    {
        private ILicenseTypeRepository _licenseTypeRepository; 
        private IUserRepository _userRepository;
        private IPurchaseOrderRepository _purchaseOrderRepository;
        private IPaytabRepository _paytabRepository;
        private ICompanyRepository _companyRepository;
        private IContactShareActivityRepository _contactShareActivityRepository;
        private IEmailTemplateRepository _emailTemplateRepository;
        private IMyCardFileRepository _myCardFileRepository;
        private IPasswordHistoryRepository _passwordHistoryRepository;

        public CompanyDashboardController(ILicenseTypeRepository licenseTypeRepository, IUserRepository userRepository, IPurchaseOrderRepository purchaseOrderRepository, IPaytabRepository paytabRepository,
            ICompanyRepository companyRepository, IContactShareActivityRepository contactShareActivityRepository, 
            IEmailTemplateRepository emailTemplateRepository, IMyCardFileRepository myCardFileRepository, IPasswordHistoryRepository passwordHistoryRepository)
        {
            if (companyRepository == (ICompanyRepository)null)
                throw new ArgumentNullException("companyRepository");
            _companyRepository = companyRepository;

            if (purchaseOrderRepository == (IPurchaseOrderRepository)null)
                throw new ArgumentNullException("purchaseOrderRepository");
            _purchaseOrderRepository = purchaseOrderRepository;

            if (paytabRepository == (IPaytabRepository)null)
                throw new ArgumentNullException("paytabRepository");
            _paytabRepository = paytabRepository;

            if (userRepository == (IUserRepository)null)
                throw new ArgumentNullException("userRepository");
            _userRepository = userRepository;

            if (licenseTypeRepository == (ILicenseTypeRepository)null)
                throw new ArgumentNullException("licenseTypeRepository");
            _licenseTypeRepository = licenseTypeRepository;

            if (contactShareActivityRepository == (IContactShareActivityRepository)null)
                throw new ArgumentNullException("contactShareActivityRepository");
            _contactShareActivityRepository = contactShareActivityRepository;

            if (emailTemplateRepository == (IEmailTemplateRepository)null)
                throw new ArgumentNullException("emailTemplateRepository");
            _emailTemplateRepository = emailTemplateRepository;

            if (myCardFileRepository == (IMyCardFileRepository)null)
                throw new ArgumentNullException("myCardFileRepository");
            _myCardFileRepository = myCardFileRepository;

            if (passwordHistoryRepository == (IPasswordHistoryRepository)null)
                throw new ArgumentNullException("passwordHistoryRepository");
            _passwordHistoryRepository = passwordHistoryRepository;
        }
        // GET: Dashboard
        public async Task<ActionResult> Index()
        {
            int userId = 0;
            int companyId = 0;
            string companyName = string.Empty;
            IList<int> userlist = null;
            int cardSharesCount = 0;
            string approved = string.Empty;

            CompanyDashboardViewModel companyViewModel = new CompanyDashboardViewModel();

            if (HttpContext.Request.IsAuthenticated)
            {
                userId = Convert.ToInt32(HttpContext.User.Identity.Name.Split('|')[1]);
            }

            if (userId > 0)
            {
                User user = new User();
                Company company = new Company();
                user = _userRepository.GetElementById(userId);

                if (user != null)
                {
                    companyId = user.CompanyId;
                                        
                    company = _companyRepository.GetFilteredElements(o => o.Id == companyId).FirstOrDefault();
                    companyName = company.Name;

                    companyViewModel.CustomerName = company.CustomerName;
                    companyViewModel.Name = company.Name;
                    companyViewModel.DomainName = company.Domain;
                    companyViewModel.EmailID = company.Email;
                    companyViewModel.BusinessTitle = company.BusinessTitle;
                    companyViewModel.MemberSince = company.CreationDate.ToString("dd MMMM yyyy");
                    ViewBag.FileName = company.LogoFileName;
                    ViewBag.CustomerType = company.CustomerType;
                    approved = company.Approved=="Yes" ? "Yes": "No";
                }

                userlist = _userRepository.GetFilteredElements(o => o.CompanyId == companyId).Select(t => t.Id).ToList();

                cardSharesCount = _contactShareActivityRepository.GetFilteredElements(o => userlist.Contains(o.SenderId)).Count();
                companyViewModel.TotalCardsShared = cardSharesCount;


            }

            PurchaseOrder po;
            po = _purchaseOrderRepository.GetFilteredElements(o => o.CompanyId == companyId).OrderByDescending(o => o.CreationDate).FirstOrDefault();
            if (po!=null)
            {
                companyViewModel.LastPurchaseDate = po.CreationDate.ToString("dd MMMM yyyy");
            }
            else
            {
                companyViewModel.LastPurchaseDate = string.Empty;
            }
            
            var poTotalAmount = _purchaseOrderRepository.GetFilteredElements(o => o.CompanyId == companyId && o.Approved==1).Sum(o => o.LicensesOrdered);
            companyViewModel.TotalPurchase = poTotalAmount;
            ViewBag.TotalPurchase = poTotalAmount;

            ViewBag.Designer = "No";

            PurchaseOrder poDesigner = _purchaseOrderRepository.GetFilteredElements(x => x.CompanyId == companyId && x.Approved == 1).FirstOrDefault();
            if (poDesigner != null)
            {
                ViewBag.Designer = "Yes";
            }
            else
            {
                if(approved=="Yes")
                {
                    ViewBag.Designer = "Yes";
                }
            }

            PurchaseOrder poAddLicense = _purchaseOrderRepository.GetFilteredElements(x => x.CompanyId == companyId).FirstOrDefault();
            if (poAddLicense != null)
            {
                ViewBag.AddLicense = "Yes";
            }

            //For Links to be white or dull
            PurchaseOrder poLatestPurchase = _purchaseOrderRepository.GetFilteredElements(x => x.CompanyId == companyId).OrderByDescending(o => o.Id).FirstOrDefault();
            if (poLatestPurchase != null)
            {
                if (poLatestPurchase.Approved == 1)
                    ViewBag.LatestPurchasedApproved = "Yes";
                else
                    ViewBag.LatestPurchasedApproved = "No";
            }
            else
            {
                ViewBag.LatestPurchasedApproved = "No";
            }

            ViewBag.CompanyName = companyName;

            ViewBag.myCardCMS = "No";
            
            Company companyCMS = await _companyRepository.GetFirstOrDefaultAsync(x => x.Id == companyId && (x.AccountType == 2 || x.AccountType == 3));
            if (companyCMS != null)
            {
                ViewBag.myCardCMS = "Yes";
                
            }


            


            return View(companyViewModel);
        }

        public ActionResult CardShareChart(int year)
        {
            //Card Shares Chart Data
            User user = null;
            IList<int> userlist = null;
            int userId = 0;
            int companyId = 0;
            IList<ContactShareActivity> cardShares = null;
            List<int> cardShareCount = new List<int>();
            if (HttpContext.Request.IsAuthenticated)
            {
                userId = Convert.ToInt32(HttpContext.User.Identity.Name.Split('|')[1]);
            }

            if (userId > 0)
            {
                user = _userRepository.GetElementById(userId);

                if (user != null)
                {
                    companyId = user.CompanyId;
                }
                userlist = _userRepository.GetFilteredElements(o => o.CompanyId == companyId).Select(t=>t.Id).ToList();

                cardShares = _contactShareActivityRepository.GetFilteredElements(o => o.CreationDate.Year == year && userlist.Contains(o.SenderId)).ToList();

                for (int i = 1; i <= 12; i++)
                {
                    cardShareCount.Add(cardShares.Count(o => o.CreationDate.Month == i));
                }
            }

            return Json(new { datalist = cardShareCount }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CompaniesChart(int year)
        {
            MyCardUnitOfWork db = new MyCardUnitOfWork();

MyCard.Web/Views/CompanyDashboard/ChangePassword.cshtml
@model MyCard.Web.Models.ChangePasswordViewModel
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_MasterLayoutAdmin.cshtml";
}

<div class=" col-xs-12">
    <p class="mar-bot20 book f-p">Minimum password length is 8 please select a combination of letters (A-z) and numbers (0-9).</p><br>
    <div class="clearfix"></div>
</div>

@using (Html.BeginForm("ChangePassword", "CompanyDashboard"))
{
    @Html.AntiForgeryToken()
    <div class=" col-xs-12">
        <div class=" col-xs-8">
            <div class="row">
                @*<p class="red-color four" hidden>@Html.ValidationSummary(false, "", new { @style = "color:red" })</p>*@
                @*<p> @Html.ValidationMessageFor(model => model.Password, "", new { @class = "red-color p-small medium" }) </p>*@
                <p id="errornotification" class="red-color p-small medium" hidden><i class=" fa fa-times-circle"></i> Please complete the highlighted mandatory fields</p>
                <p id="errorpasswordmatch" class="red-color p-small medium" hidden><i class=" fa fa-times-circle"></i> @MyCard.Web.Resources.ErrorMessages.ComparePasswordErrorMessage</p>
                <p id="ppassworderror" class="red-color p-small medium" hidden><i class=" fa fa-times-circle"></i> @MyCard.Web.Resources.ErrorMessages.InvalidPassword</p>
                @if (!string.IsNullOrEmpty(ViewBag.Message))
                {
                    <p id="errornotification" class="red-color p-small medium"><i class=" fa fa-times-circle"></i> @ViewBag.Message</p>
                }

            </div>
        </div>
        <div class="clearfix"></div>

        <div class=" col-xs-5">
            <div class="row">
                @Html.EditorFor(model => model.OldPassword, new { htmlAttributes = new { placeholder = "Old Password" } })

            </div>
        </div>
        <div class="clearfix"></div>

        <div class=" col-xs-5">
            <div class="row">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { placeholder = "New Password" } })
            </div>
        </div>
        <div class="clearfix"></div>

        <div class=" col-xs-5">
            <div class="row">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { placeholder = "Confirm New Password" } })
            </div>
        </div>
        <div class="clearfix"></div>

        <div class=" col-xs-5">
            <div class="row">

                <div>
                    <div class="pull-right"> <button type="button" class="submit" name="changepassword" id="changepassword">@MyCard.Web.Resources.CaptionsAll.ChangePassword</button> </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>

    </div>


}

<script type="text/javascript">

    $(document).ready(function () {

        // Attach click handler to the submit button:
        $('#changepassword').click(function () {
            if ($('#OldPassword').val() == '') {
                $('#OldPassword').css('border-color', 'red');
                $('#errornotification').show();
                return false;
            }
            else {
                $('#OldPassword').css('border-color', '');
                $('#errornotification').hide();
            }
            
            ///////////////
            if ($('#Password').val() == '') {
                $('#Password').css('border-color', 'red');
                $('#ConfirmPassword').css('border-color', 'red');
                $('#errornotification').show();
                return false;
            }
            else {
                $('#Password').css('border-color', '');
                $('#ConfirmPassword').css('border-color', '');
                $('#errornotification').hide();
            }
            /////////////////
            if (!validatePassword($('#Password').val())) {
                $('#Password').css('border-color', 'red');
                $('#ConfirmPassword').css('border-color', 'red');
                $('#ppassworderror').show();
                return false;
            }
            else {
                $('#Password').css('border-color', '');
                $('#ConfirmPassword').css('border-color', '');
                $('#ppassworderror').hide();
            }
            /////////////////
            ///////////////
            //if ($('#ConfirmPassword').val() == '') {
            //    $('#ConfirmPassword').css('border-color', 'red');
            //    $('#errornotification').show();
            //}
            //else {
            //    $('#ConfirmPassword').css('border-color', '');
            //}
            ///////////////

            //if ($('#OldPassword').val() == '' || $('#Password').val() == '' || $('#ConfirmPassword').val() == '') {
            //    $('#errornotification').show();
            //    return false;
            //}
            //else {
            //    $('#errornotification').hide();
            //}
            ///////////////
            if ($('#Password').val() != $('#ConfirmPassword').val()) {
                $('#ConfirmPassword').css('border-color', 'red');
                $('#errorpasswordmatch').show();
                return false;
            }
            else {
                $('#ConfirmPassword').css('border-color', '');
                $('#errorpasswordmatch').hide();
            }
            ////////
            $("form").submit();
        });

        function validatePassword(sPassword) {
            var filter = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/;
            if (filter.test(sPassword)) {
                return true;
            }
            else {
                return false;
            }
        }
    });
</script> 

MyCard.Web/Views/CompanyDashboard/ChangePasswordThanks.cshtml
@{
    ViewBag.Title = "ChangePasswordThanks";
    Layout = "~/Views/Shared/_MasterLayoutAdmin.cshtml";
}

<div  class=" col-xs-8">
    <p>@MyCard.Web.Resources.CaptionsAll.ChangePasswordThanksMessage</p>
</div>

<div>
    <a href="@Url.Action("Login", "CompanyDashboard")" class="txt-bold color-blue">@MyCard.Web.Resources.CaptionsAll.LoginButton</a>
</div>

MyCard.Web/Views/CompanyDashboard/CreatePasswordThanks.cshtml
@{
    ViewBag.Title = @MyCard.Web.Resources.CaptionsAll.CreatePasswordThanksTitle;
    Layout = "~/Views/Shared/_MasterLayoutAdmin.cshtml";
}
<div class=" col-xs-8">
    <p>You have created your password, you can <a href="@Url.Action("Login", "CompanyDashboard")" class="txt-bold color-blue">login</a> to your account.</p>
</div>


@*<div class=" col-xs-8">
    <a href="@Url.Action("Login", "Registration")" class="txt-bold color-blue">Login</a>
</div>*@

MyCard.Web/Views/CompanyDashboard/EmployeesListing.cshtml
@model MyCard.Web.Models.EmployeeListingViewModel
@{
    ViewBag.Title = @MyCard.Web.Resources.CaptionsAll.EmployeeListingTitle;
    Layout = "~/Views/Shared/_MasterLayoutAdmin.cshtml";
}

@using (Ajax.BeginForm("EmployeesListing", "CompanyDashboard", new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "EmployeesDiv" }))
{

    <div class="col-md-12">
        <h3>Employee Listing</h3>
        <div class="row">
            <div class="col-md-3">
                <div class="">
                    @Html.TextBoxFor(m => m.SearchString, Model.SearchString, new { @placeholder = "Search employee" })
                </div>
            </div>

            <div class="col-md-3">
                <div class="row">
                    @Html.TextBox("DateFrom", "", new { @placeholder = "From Date" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="">
                    @Html.TextBox("DateTo", "", new { @placeholder = "To Date" })
                </div>
            </div>
            <div class="col-md-2">
                <div class="">
                    <input type="button" id="SearchButton" Name="SearchButton" value="Search" />
                </div>
            </div>
        </div>
    </div>

    <div id="EmployeesDiv">
        @Html.Partial("_PartialEmployees", Model)

    </div>
}


<div style="top:25%;" class="modal fade popup_view" id="crosspopup_view" name="crosspopup_view">
    <div class="modal-dialog">
        <div style="border:none;" class="modal-content">
            <div class="col-xs-12">
                <div class="green-bg popup">
                    <div class="col-xs-3"><img alt="tick" src="~/img/admin/ask.png" class="img-responsive center-block" /></div>
                    <div class="col-xs-9">
                        <h4 class="color-white five"> @MyCard.Web.Resources.CaptionsAll.DeActivateEmployeeMessage1</h4>
                        <h4 class="color-white three">
                            @MyCard.Web.Resources.CaptionsAll.DeActivateEmployeeMessage2
                        </h4>
                    </div>
                    <div class="clear"></div>
                </div>
                <button type="button" class=" submit small pull-right" id="btnYesConfirmYesNo">OK <i class=" fa fa-next"></i></button>
                <button type="button" class=" submit small pull-right mar-right10" id="btnNoConfirmYesNo">Back <i class=" fa fa-next"></i></button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    //$(".pager").click(function (evt) {
    //    var pageindex = $(evt.target).data("pageindex");
    //    $("#CurrentPageIndex").val(pageindex);
    //    evt.preventDefault();
    //    $("form").submit();
    //});
    function pagerclick(pindex) {
        var pageindex = pindex;
        $("#CurrentPageIndex").val(pageindex);
        //evt.preventDefault();
        $("form").submit();

    }

    function PageSizeChange() {
        $("#CurrentPageIndex").val(0);
        $("form").submit();
    }

    $("#SearchString").keyup(function (event) {
        //if (event.keyCode == 13) {
            $("#CurrentPageIndex").val(0);
            $("form").submit();
        //}
    });

    $("#SearchButton").click(function (event) {
        $("#CurrentPageIndex").val(0);
        $("form").submit();
    });

    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
        $("#DateFrom").datepicker({ dateFormat: 'd-M-yy' }).val();
        $("#DateTo").datepicker({ dateFormat: 'd-M-yy' }).val();
    })

    function Paging() {
        $("form").submit();
    }

    function backFunction() {
        $('#crosspopup_view').modal('hide');
    }

    function showAlert(item) {
        //$('#crosspopup_view').modal({ backdrop: 'static', keyboard: false });
        var r = confirm("Are you sure you want to deactivate employee!");
        if (r == true) {
            deActivateEmployee(item)
            //document.getElementById("hfCurrentPageIndex").value = index;
            //document.forms[0].submit();
            $("form").submit();
        }
        else {
            alert("You pressed Cancel!");
        }
    }

    function deActivateEmployee(elem) {
        var isDone = 0;
        var uid = elem;//$(elem).data('itemid');
        $.ajax({
            type: 'POST',
            url: '@Url.Action("DeactivateEmployee", "CompanyDashboard")',
        data: { status: isDone,userid:uid },
        //data: { approved: isDone},
        success: function(res) {
            console.log(res);
        }
        });
    }

    function AsyncConfirmYesNo(elem) {
        var $confirm = $("#crosspopup_view");
        $confirm.modal('show');
        $("#btnYesConfirmYesNo").off('click').click(function () {
            deActivateEmployee(elem);
            $confirm.modal("hide");
            Paging();
        });
        $("#btnNoConfirmYesNo").off('click').click(function () {
            $confirm.modal("hide");
        });
    }

</script>

MyCard.Web/Views/CompanyDashboard/ResetPasswordExpired.cshtml
@{
    ViewBag.Title = "ResetPasswordExpired";
    Layout = "~/Views/Shared/_MasterLayoutAdmin.cshtml";
}

<div>
    <p>@MyCard.Web.Resources.CaptionsAll.ResetPasswordExpiredMessage</p>
</div>

<div>
    <a href="@Url.Action("Login", "Default")" class="txt-bold color-blue">@MyCard.Web.Resources.CaptionsAll.LoginButton</a>
</div>

MyCard.Web/Views/CompanyDashboard/ResetPasswordThanks.cshtml
@{
    ViewBag.Title = @MyCard.Web.Resources.CaptionsAll.CreatePasswordThanksTitle;
    Layout = "~/Views/Shared/_MasterLayoutAdmin.cshtml";
}
<div div class=" col-xs-12">
    <div>
        <p>@MyCard.Web.Resources.CaptionsAll.ResetPasswordThanksMessage</p>
    </div>

    <div>
        <a href="@Url.Action("Login", "CompanyDashboard")" class="txt-bold color-blue">Login</a>
    </div>
</div>